---
- name: Install Java
  become: yes
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Copy Elasticsearch GPG key ASCII to target
  become: yes
  ansible.builtin.copy:
    src: GPG-KEY-elasticsearch
    dest: /etc/apt/trusted.gpg.d/elasticsearch.asc
    owner: root
    group: root
    mode: '0644'

- name: Convert Elasticsearch GPG key to binary
  become: yes
  ansible.builtin.command:
    cmd: >
      gpg --batch --yes --dearmor
      --output /etc/apt/trusted.gpg.d/elasticsearch.gpg
      /etc/apt/trusted.gpg.d/elasticsearch.asc
  args:
    creates: /etc/apt/trusted.gpg.d/elasticsearch.gpg

- name: Add Elasticsearch APT repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    filename: elastic-8.x
    state: present
    update_cache: yes

- name: Install ELK stack packages
  become: yes
  ansible.builtin.apt:
    name:
      - elasticsearch
      - logstash
      - kibana
    state: present
    update_cache: yes

# Обеспечиваем шаблоны конфигов
- name: Configure Elasticsearch
  become: yes
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Elasticsearch

- name: Configure JVM options for Elasticsearch
  become: yes
  ansible.builtin.template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options.d/override.options
    owner: root
    group: root
    mode: '0644'
  notify: Restart Elasticsearch

- name: Configure Kibana
  become: yes
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Kibana

- name: Configure Logstash
  become: yes
  ansible.builtin.template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Logstash


- name: Ensure Elasticsearch config, data and log directories exist
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'
  loop:
    - /etc/elasticsearch
    - /var/lib/elasticsearch
    - /var/log/elasticsearch

- name: Start and enable ELK services
  become: yes
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - logstash

- name: Open firewall ports for ELK
  become: yes
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 9200
    - 5601
    - 5044
