---
- name: Install PostgreSQL from Ubuntu repositories
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present
    update_cache: yes
